### ISSUE TITLE
MinimumRange not used

### ISSUE THREAD

**Issue by daniels1989** [Blothorn/FTD#1]
MinimumRange seems to not be mentioned anywhere else in the code, apart from in the initial WeaponSystem config, unless it's misspelled elsewhere (Did a quick Ctrl+F to look for it.)

MaximumRange would be appreciated too.

**Comment by isturdy** [comment]
Sorry for the delay---minimum and maximum range were replaced by a system that dynamically calculates range based on speed and endurance, which gives better results for off-bore launches (which have reduced range against targets further off-bore). I just forgot to remove that line from the default config.

**Comment by Blothorn** [comment]
Sorry for the delay---minimum and maximum range were replaced by a system that dynamically calculates range based on speed and endurance, which gives better results for off-bore launches (which have reduced range against targets further off-bore). I just forgot to remove that line from the default config.
